# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('EmpId', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('City', models.CharField(max_length=128)),
            ],
        ),
    ]
