# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('MobileNumber', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
    ]
